using AverageProblem;
using BasicCalculationProblem;
using CommentProgram;
using DivisionByZeroProblem;
using DivisionFactorProblem;
using DoubleValueProblem;
using EquivalentProblem;
using FloatValueProblem;
using HelloWorldProgram;
using MultiplicationFactorProblem;
using MultiplicationTableProblem;
using OrderOfPriorityProblem;
using PrintLineProgram;
using RandomNumberProblem;
using ReadUserInputProgram;
using ReverseOrderProblem;
using SphereCalculationProgram;
using SquareNumberProblem;
using StoreUserInputProgram;
using TemperatureConversionProblem;


//HelloWorld.HelloWorldMethod();
//PrintLine.PrintLineMethod();
//ReadUserInput.Solution();
//StoreUserInput.Solution();
//Comment.Solution();
//SphereCalculation.Solution();
//BasicCalculation.Solution();
//ReverseOrder.Solution();
//TemperatureConversion.Solution();
//DoubleValue.Solution();
//FloatValue.Solution();
//MultiplicationTable.Solution();
//RandomNumber.Solution();
//SquareNumber.Solution();
//MultiplicationFactor.Solution();
//DivisionFactor.Solution();
//DivisionByZero.Solution();
//OrderOfPriority.Solution();
//Average.Solution();
Equivalent.Solution();